### ISSUE TITLE
Compatible with react-pdf-html

### ISSUE THREAD

**Issue by imcvampire** [josippapez/react-pdf-html#1]
I would like to use [react-pdf-html](https://www.npmjs.com/package/react-pdf-html) to render some custom html code in PDF but seems like it isn't compatible with your library

**Comment by josippapez** [comment]
Hi @imcvampire. Thanks for trying out my library.
I've implemented my library as a wrapper around [react-pdf-renderer](https://github.com/diegomura/react-pdf) so It only uses the default components that react-pdf-renderer provides. The library you mentioned adds a new component on top of the react-pdf-renderer library hence why you can't use it with my lib.

I would suggest you try to use react-pdf-renderer as you would normally when creating PDFs but with imports from my lib so you can display it in your app without building the PDF first as mentioned in the README
```tsx
import React from "react";
// this replaces @react-pdf/renderer components
import { Document, Image, Page, View } from "@rawwee/react-pdf-html";

const MyDocument = () => (
  <Document>
    <Page>
      <Text>Hello, World!</Text>
    </Page>
  </Document>
);

// You can then render the component as an HTML component
const App = () => <MyDocument />;

export default App;
```
